on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-tag
  cancel-in-progress: false

jobs:
  changes:
    name: Detect version change
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.filter.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            version:
              - 'VERSION'

  tag-release:
    name: Tag release on version change
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.version == 'true' }}
    permissions:
      contents: write
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract Version
        id: extract_version
        run: |
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          generate_release_notes: true

  perform-release:
    name: Perform release
    needs: tag-release
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.tag-release.outputs.version }}
    permissions:
      contents: write
      packages: write
      id-token: write
